config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'blog/:id' => 'blog#show', as: :blog
  get 'blog/:id/comments' => 'blog#comments', as: :blog_comments
  post 'blog/:id/comments' => 'blog#comment', as: :blog_comment
  get 'blog/:id/follow' => 'blog#follow', as: :follow_blog
  get 'blog/:id/like' => 'blog#like', as: :like_blog
  get 'blog/:id/visit' => 'blog#visit', as: :visit_blog
  get 'blog/:id/has_new' => 'blog#has_new', as: :has_new

  get 'user/profile', as: :user_profile
  get 'user/profile/edit' => 'user#edit_profile', as: :edit_user_profile
  patch 'user/profile/edit' => 'user#patch_profile'
  get 'user/onboard' => 'user#onboard', as: :onboarding
  patch 'user/onboard' => 'user#patch_onboard'

  get 'user/:id/follow' => 'user#follow', as: :follow_user

  get 'user/likes'
  get 'user/:id/likes' => 'user#likes'

  get 'user/friends'
  get 'user/:id/friends' => 'user#friends'

  get 'user/blogs'
  get 'user/:id/blogs' => 'user#blogs'

  get 'user/:id' => 'user#profile', as: :user
  post 'user/notifications/read' => 'user#read_notifications', as: :read_notifications

  post 'post/:id/comment' => 'post#comment', as: :post_comment
  get 'post/:id' => 'post#show', as: :post
  get 'post/:id/like' => 'post#like', as: :like_post
  get 'post/:id/visit' => 'post#visit', as: :post_visit

  get 'share/scrape', as: :scrapper
  post 'share/share', as: :share
  get 'share/mentionables', as: :mentionables

  get 'feed/discover', as: :discover
  get 'feed/discover/posts' => 'feed#posts', as: :discover_posts
  get 'feed/discover/blogs' => 'feed#blogs', as: :discover_blogs
  get 'feed/discover/users' => 'feed#users', as: :discover_users
  get 'feed/discover/tags' => 'feed#tags', as: :discover_tags

  get 'search' => 'feed#search', as: :search

  root 'feed#home'
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  before_action :authenticate_user!

  def home
    @feed = PublicActivity::Activity.where(key: ['user.post.shared'])
                                    .where(trackable_id: current_user.followees(User),  trackable_type: 'User')
                                    .or(PublicActivity::Activity.where(owner_id: current_user.followees(Blog), owner_type: 'Blog'))
                                    .order(created_at: :desc)
                                    .paginate(page: params[:page])
                                    .per_page(10)

    begin
      @blogs = current_user.followees(Blog).sort_by(&:title)
    rescue
      @blogs = current_user.followees(Blog)
    end
  end

  def discover
    @feed = Post.limit(24).order("RANDOM()")
    #@blogs = Blog.order(followers_count: :desc).limit(10)
    @blogs = Blog.limit(10).order("RANDOM()")
    @tags = ActsAsTaggableOn::Tag.most_used(30)
    @users = User.all.where.not(id: current_user.id).order('followers_count DESC').limit(8)
  end

  def blogs
    @blogs = Blog.order(followers_count: :desc).limit(60)
  end

  def posts
    #@feed = Post.order(comments_count: :desc, likers_count: :desc, created_at: :desc).limit(20)
    @feed = Post.limit(40).order("RANDOM()")
  end

  def users
    @users = User.all.where().not(id: current_user.id).order(followers_count: :desc).limit(12)
  end

  def tags
    @tags = ActsAsTaggableOn::Tag.most_used(300)
  end

  def search
    @users = User.search(params[:query])
    @blogs = Blog.search(params[:query]) + Blog.tagged_with(params[:query])
    @posts = Post.search(params[:query]) + Post.tagged_with(params[:query])

    @posts.uniq! { |post| post.id }
  end
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/views/feed/blogs.html.erb
<div class="feeds discover multiply">
	<div class="blogs">
		<h1 class="section">Trending blogs</h1>
		<ul class="activity-feed">
			<%= render partial: 'partials/discover_blog', collection: @blogs %>
		</ul>
	</div>
</div>

app/views/feed/discover.html.erb
<div class="feeds discover">
	<div class="posts fun">
		<h1 class="section">Trending posts <%= link_to "View More", discover_posts_path %></h1>
		<ul class="activity-feed">
			<%= render partial: 'partials/post', collection: @feed  %>
		</ul>
	</div>

	<div class="others">
		<div class="blogs fun">
			<h1 class="section">Popular Blogs <%= link_to "View More", discover_blogs_path %></h1>
			<ul>
				<%= render partial: 'partials/discover_blog', collection: @blogs %>
			</ul>
		</div>

		<div class="users">
			<h1 class="section">Find Friends <%= link_to "View More", discover_users_path %></h1>
			<div>
				<%= render partial: 'partials/user', collection: @users, locals: { classes: 'mini' } %>
			</div>
		</div>

		<div class="tags">
			<h1 class="section">Trending Tags <%= link_to "View More", discover_tags_path %></h1>
			<ul>
				<%= render partial: 'partials/tag', collection: @tags %>
			</ul>
		</div>

	</div>
</div>

app/views/feed/home.html.erb
<div class="feeds home">
	<ul class="activity-feed" data-infinity="true">
		<% if @feed.empty? %>
			<h1>Welcome Aboard!</h1>
			<p>Get started by <%= link_to 'discovering', discover_path %> blogs and users to follow.</p>
		<% end %>

		<% @feed.each do |post| %>
			<%= render_activity(post, locals: { user: current_user }) %>
		<% end %>

		<%= will_paginate @feed %>
	</ul>

	<div class="sidebar">
		<div class="blogs">
			<header>
				<h1>Following</h1> <%= link_to 'Manage', user_blogs_path %>
			</header>

			<ul class="following__tags__">
				<% if @blogs.empty?  %>
					<h3>You aren't following any blogs.</h3>
					<p>Try <%= link_to 'discovering', discover_path %> new blogs.</p>
				<% end %>

				<% @blogs.each do |blog| %>
					<li data-id="<%= blog.id %>">
            <%= link_to blog.title, visit_blog_path(blog) %>
            <span style="display: none;">New</span>
					</li>
				<% end %>
			</ul>
		</div>

		<%= render 'partials/footer' %>
	</div>
</div>

app/views/feed/posts.html.erb
<div class="feeds discover multiply">
	<div class="posts">
		<h1 class="section">Trending posts</h1>
		<ul class="activity-feed">
			<%= render partial: 'partials/post', collection: @feed  %>
		</ul>
	</div>
</div>

app/views/feed/search.html.erb
<div class="search-results">
	<h1>Search Results</h1>

	<% if @posts.empty? && @blogs.empty? && @users.empty? %>
		<p>No results were found for "<%= params[:query] %>"</p>
	<% end -%>

	<% unless @posts.empty? %>
	<div class="posts">
		<h2>Posts</h2>
		<ul class="activity-feed">
			<%= render partial: 'partials/post', collection: @posts %>
		</ul>
	</div>
	<% end -%>

	<div class="sidebar">
		<% unless @blogs.empty? %>
		<h2>Blogs</h2>
		<ul class="blogs-feed">
			<%= render partial: 'partials/discover_blog', collection: @blogs %>

		</ul>
		<% end %>

		<% unless @users.empty? %>
		<h2>Users</h2>
		<div>
			<%= render partial: 'partials/user', collection: @users, locals: { classes: 'mini' }  %>
		</div>
		<% end -%>
	</div>
</div>

app/views/feed/tags.html.erb
<div class="feeds discover multiply">
	<div class="tags">
		<h1 class="section">Trending Tags</h1>
		<ul>
			<%= render partial: 'partials/tag', collection: @tags %>
		</ul>
	</div>
</div>

app/views/feed/users.html.erb
<div class="feeds discover users">
	<h1 class="section">Popular Users</h1>
	<div class="bro">
		<%= render partial: 'partials/user', collection: @users, locals: { classes: 'vertical' } %>
	</div>
</div>