config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'blog/:id' => 'blog#show', as: :blog
  get 'blog/:id/comments' => 'blog#comments', as: :blog_comments
  post 'blog/:id/comments' => 'blog#comment', as: :blog_comment
  get 'blog/:id/follow' => 'blog#follow', as: :follow_blog
  get 'blog/:id/like' => 'blog#like', as: :like_blog
  get 'blog/:id/visit' => 'blog#visit', as: :visit_blog
  get 'blog/:id/has_new' => 'blog#has_new', as: :has_new

  get 'user/profile', as: :user_profile
  get 'user/profile/edit' => 'user#edit_profile', as: :edit_user_profile
  patch 'user/profile/edit' => 'user#patch_profile'
  get 'user/onboard' => 'user#onboard', as: :onboarding
  patch 'user/onboard' => 'user#patch_onboard'

  get 'user/:id/follow' => 'user#follow', as: :follow_user

  get 'user/likes'
  get 'user/:id/likes' => 'user#likes'

  get 'user/friends'
  get 'user/:id/friends' => 'user#friends'

  get 'user/blogs'
  get 'user/:id/blogs' => 'user#blogs'

  get 'user/:id' => 'user#profile', as: :user
  post 'user/notifications/read' => 'user#read_notifications', as: :read_notifications

  post 'post/:id/comment' => 'post#comment', as: :post_comment
  get 'post/:id' => 'post#show', as: :post
  get 'post/:id/like' => 'post#like', as: :like_post
  get 'post/:id/visit' => 'post#visit', as: :post_visit

  get 'share/scrape', as: :scrapper
  post 'share/share', as: :share
  get 'share/mentionables', as: :mentionables

  get 'feed/discover', as: :discover
  get 'feed/discover/posts' => 'feed#posts', as: :discover_posts
  get 'feed/discover/blogs' => 'feed#blogs', as: :discover_blogs
  get 'feed/discover/users' => 'feed#users', as: :discover_users
  get 'feed/discover/tags' => 'feed#tags', as: :discover_tags

  get 'search' => 'feed#search', as: :search

  root 'feed#home'
end

app/views/partials/_blog.html.erb
<li>
	<div class="title">
		<%= link_to blog.title, blog %>
	</div>
	<div class="actions">
		<%= render 'partials/follow_button', locals: { subject: blog, classes: 'btn' } %>
	</div>
</li>

app/views/partials/_discover_blog.html.erb
<li data-id="<%= discover_blog.id %>">
	<div class="title">
		<%= link_to discover_blog.title, visit_blog_path(discover_blog) %>

		<span>
			<%= image_tag 'users.png' %> <%= content_tag :span, discover_blog.followers_count, 'data-blog-followers': discover_blog.id %>

			<% display_updates ||= false %>
      <% if display_updates %>
			  <span style="display: none;" class="status">New</span>
      <% end -%>
		</span>

	</div>


	<div class="actions">
		<%= render 'partials/follow_button', locals: { subject: discover_blog, classes: 'btn small' } %>
	</div>
</li>

app/views/partials/_follow_button.html.erb
<% subject = locals[:subject] %>
<%= link_to conditional_label(current_user.follows?(subject), 'Following', 'Follow'), 
	send("follow_#{subject.class.to_s.underscore}_path", subject), 
	class: "btn #{locals[:classes]} #{'on' if current_user.follows?(subject)}", 
	remote: true, 
	"data-#{subject.class.to_s.underscore}": subject.id 
%>

app/views/partials/_header.html.erb
<header id="top" class="<%= local_assigns.fetch :classes, '' %>">
	<div class="logo">
		<%= link_to root_path  do %>
			<%= image_tag 'logo.png' %>
		<% end -%>
	</div>

	<% unless current_user.nil? %>

	<%= form_tag(search_path, method: 'get', class: 'search') do %>
		<input type="text" name="query" id="query" placeholder="Search on Blogular (tags, people, blogs)" value="<%= params[:query] %>">
	<% end -%>

	<div class="tools">
		<%= link_to discover_path, class: 'discover' do %>
			<%= image_tag 'discover.png' %> <span>Discover</span>
		<% end %>

		<button class="btn share" data-shareTool>Share</button>

		<button class="btn notifications <%= conditional_label(@notifications.where(read: false).exists?, 'has', '') %>">
			<% unless @notifications.where(read: false).exists? %>
				<%= image_tag 'notifications-off.png' %>
			<% else  %>
				<%= image_tag 'notifications-on.png' %>
				<span><%= @notifications.where(read: false).count %></span>
			<% end -%>

		</button>

		<span class="profile" data-dropdown="profile-menu">
			<%= image_tag current_user.profile.avatar.url(:thumb) %></button>
		</span>

		<ul id="profile-menu" class="profile-menu">
			<li>
				<%= link_to 'Profile', current_user %>
			</li>
			<li>
				<%= link_to 'Edit Profile', edit_user_profile_path %>
			</li>
			<li>
				<%= link_to 'Logout', destroy_user_session_path, method: :delete %>
			</li>
		</ul>

		<ul class="notifications">
			<% if @notifications.empty? %>
				<li>You have no notifications.</li>
			<% end -%>

			<% @notifications.each do |notification| %>
				<%= render_activity(notification, locals: { user: current_user }) %>
			<% end %>
		</ul>
	</div>
	<% end -%>
</header>

app/views/partials/_modals.html.erb
<div class="modal share" data-modal="shareTool">
	<%= form_tag(share_path, remote: true) do %>
		<input type="text" name="url" placeholder="Paste URL here to Share">
		<%= image_tag 'spinner.gif', class: 'spinner' %>

		<div class="preview">
			<img data-modal-image>

			<div class="content">
				<h1 data-modal-title></h1>
				<p data-modal-description></p>
			</div>

			<div class="options">
				<div class="left">
					<input type="text" name="tags" placeholder="Comma-separated tags">

					<label>
						Follow blog <input type="checkbox" name="follow">
					</label>
				</div>

				<div class="right">
					<button class="btn small" data-modal-approve data-disable-with="Sharing...">
						Share
					</button>

					<button class="btn small red" data-modal-cancel>
						Cancel
					</button>
				</div>
			</div>
		</div>
	<% end %>

	<div class="success">
		<h1>Your post was shared successfully.</h1>
	</div>

</div>

<div data-overlay class="overlay"></div>

app/views/partials/_post.html.erb
<li class="activity-link" data-activity="link" data-image="<%= post.image.url(:large) %>" data-post-id="<%= post.id %>">
	<header>
		<div>
			<b><%= link_to post.user.profile.username, user_path(post.user) %></b> shared
		</div>

		<time title="<%= post.created_at %>" datetime="<%= post.created_at %>"><%= time_ago_in_words post.created_at %> ago</time>
	</header>

	<h1><%= link_to post_visit_path(post) do %>
    <%= post.title ? post.title : (post.blog && post.blog.title ? post.blog.title : "Untitled") %>
  <% end %>
  </h1>
	<ul class="actions">
		<li>
			<%= link_to like_post_path(post), remote: true, class: "like #{'liked' if current_user.likes?(post)}" do %>
				<span><%= post.likers_count %></span>
			<% end %>
		</li>

		<li>
			<%= link_to post_path(post), class: 'comment' do %>
				<span><%= post.comments.count %></span>
			<% end -%>
		</li>
	</ul>
</li>

app/views/partials/_single_comment.html.erb
<% comment = locals[:comment] %>

<li id="comment-<%= comment.id %>">
	<%= link_to comment.user do %>
	<%= image_tag comment.user.profile.avatar(:thumb) %>
	<% end -%>
	<div>
		<h2><%= link_to comment.user.profile.name, comment.user %></h2>
		<p><%= raw linkify(comment.comment) %></p>
		<footer>
			<time title="<%= comment.created_at %>" datetime="<%= comment.created_at %>"><%= time_ago_in_words comment.created_at %> ago</time>
		</footer>
	</div>
</li>

app/views/partials/_tag.html.erb
<li style="background-color: <%= random_color %>">
	<%= link_to "#{tag} (#{Post.tagged_with(tag.name).size})", search_path(query: tag.name) %>
</li>

app/views/partials/_user.html.erb
<div class="user-pill <%= "#{classes}" if defined?(classes) %>">
	<div class="image">
		<%= link_to user do %>
			<%= image_tag user.profile.avatar.url(:medium) %>
		<% end -%>
	</div>
	<div class="info">
		<h1>
			<%= link_to user do %>
				@<%= user.profile.username %>
			<% end %>
		</h1>

		<p>
			<%= truncate user.profile.bio %>
		</p>

		<div>
			<% if current_user.profile.id != user.id %>
				<%= render 'partials/follow_button', locals: { subject: user, classes: 'small' } %>
			<% end -%>
		</div>
	</div>
</div>