config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'blog/:id' => 'blog#show', as: :blog
  get 'blog/:id/comments' => 'blog#comments', as: :blog_comments
  post 'blog/:id/comments' => 'blog#comment', as: :blog_comment
  get 'blog/:id/follow' => 'blog#follow', as: :follow_blog
  get 'blog/:id/like' => 'blog#like', as: :like_blog
  get 'blog/:id/visit' => 'blog#visit', as: :visit_blog
  get 'blog/:id/has_new' => 'blog#has_new', as: :has_new

  get 'user/profile', as: :user_profile
  get 'user/profile/edit' => 'user#edit_profile', as: :edit_user_profile
  patch 'user/profile/edit' => 'user#patch_profile'
  get 'user/onboard' => 'user#onboard', as: :onboarding
  patch 'user/onboard' => 'user#patch_onboard'

  get 'user/:id/follow' => 'user#follow', as: :follow_user

  get 'user/likes'
  get 'user/:id/likes' => 'user#likes'

  get 'user/friends'
  get 'user/:id/friends' => 'user#friends'

  get 'user/blogs'
  get 'user/:id/blogs' => 'user#blogs'

  get 'user/:id' => 'user#profile', as: :user
  post 'user/notifications/read' => 'user#read_notifications', as: :read_notifications

  post 'post/:id/comment' => 'post#comment', as: :post_comment
  get 'post/:id' => 'post#show', as: :post
  get 'post/:id/like' => 'post#like', as: :like_post
  get 'post/:id/visit' => 'post#visit', as: :post_visit

  get 'share/scrape', as: :scrapper
  post 'share/share', as: :share
  get 'share/mentionables', as: :mentionables

  get 'feed/discover', as: :discover
  get 'feed/discover/posts' => 'feed#posts', as: :discover_posts
  get 'feed/discover/blogs' => 'feed#blogs', as: :discover_blogs
  get 'feed/discover/users' => 'feed#users', as: :discover_users
  get 'feed/discover/tags' => 'feed#tags', as: :discover_tags

  get 'search' => 'feed#search', as: :search

  root 'feed#home'
end

app/models/post.rb
class Post < ActiveRecord::Base
  include PublicActivity::Common
  include PgSearch

  acts_as_likeable
  acts_as_commentable
  acts_as_taggable

  pg_search_scope :search, 
                  against: [:title], 
                  using: {
                    tsearch: { prefix: true }, 
                    trigram: {}
                  }

  has_attached_file :image, styles: { large: "600x300#", medium: "300x150#" }
  validates_attachment_content_type :image, content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']
  
  belongs_to :user
  belongs_to :blog, counter_cache: true
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :authenticate_user!

  def show
    @post = Post.find(params[:id])
  end

  def like
    @post = Post.find(params[:id])
    @liked = current_user.toggle_like! @post
  end

  def visit
    @post = Post.find(params[:id])

    unless @post.blog.nil?
      @receipt = ReadState.find_or_initialize_by(user_id: current_user.id, blog_id: @post.blog.id)
      @receipt.last_read = DateTime.now
      @receipt.save
    end

    frameoptions = HTTParty.get(@post.url).headers['x-frame-options'];
    redirect = false

    unless frameoptions.nil?
       if frameoptions == 'SAMEORIGIN' or frameoptions == 'sameorigin'
          redirect = true
        end
    end

    unless redirect
      render 'post/visit', layout: false
    else
      redirect_to @post.url
    end


  end

  def comment
    @post = Post.find(params[:id])
    comment = @post.comments.create
    comment.comment = params[:comment]
    comment.user = current_user
    comment.save
    @comment = comment

    unless params[:mentions].nil?
      params[:mentions].each do |mention|
        user = User.find(mention)
        @comment.mention!(user)
        user.create_activity action: 'mention', recipient: @comment, owner: current_user
      end
    end
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/post/comment.js.erb
$('.comments ul').prepend($('<%= j render 'partials/single_comment', locals: { comment: @comment }  %>')).hide().fadeIn('slow');
$('.comments textarea').val('');
$('.expanded').removeClass('expanded');
$('.comments .mentions').empty();

app/views/post/like.js.erb
<% if @liked %>
	$('[data-post-id="<%= @post.id %>"] .actions .like').addClass('liked').find('span').text('<%= @post.likers_count + 1 %>');
<% else %>
	$('[data-post-id="<%= @post.id %>"] .actions .like').removeClass('liked').find('span').text('<%= @post.likers_count - 1 %>');
<% end %>

$('[data-label-update="<%= @post.id %>"]').text('<%= conditional_label(@liked, 'Liked', 'Like') %>');

app/views/post/show.html.erb
<div class="post" data-post>
	<div class="user">
		<%= link_to @post.user do %>
			<%= image_tag @post.user.profile.avatar(:thumb) %>
		<% end %>
	</div>

	<header class="<%= 'collapsed' unless @post.image.present? %>" style="background-image: url(<%= @post.image.url(:large) %>)" data-post-id="<%= @post.id %>">
		<div>
			<b><%= link_to @post.user.profile.name, @post.user %></b> shared
		</div>

		<time title="<%= @post.created_at %>" datetime="<%= @post.created_at %>"><%= time_ago_in_words @post.created_at %> ago</time>

		<h1><%= link_to @post.title, post_visit_path(@post) %></h1>

		<ul class="actions">
			<li>
				<%= link_to like_post_path(@post), remote: true, class: "like #{'liked' if current_user.likes?(@post)}" do %>
					<span><%= @post.likers_count %></span>
 				<% end %>
			</li>
		</ul>
	</header>

	<% unless @post.blog.nil? %>
	<div class="sidebar">
		<div class="blog">
			<header>
				<div class="status">
					Posted on
				</div>
				<h1><%= link_to @post.blog.title, @post.blog %></h1>
				<%= render 'partials/follow_button', locals: { subject: @post.blog } %>
			</header>
		</div>
		<%= render 'partials/footer' %>
	</div>
	<% end %>

	<div class="comments">
		<header>
			<h1>Comments</h1>
		</header>

		<%= form_tag post_comment_path(@post), remote: true do %>
			<%= text_area_tag 'comment', nil, rows: 1, placeholder: 'Comment or tag someone on this post', 'data-mentionable': 'true'  %>
			<%= submit_tag 'Post comment', class: 'btn solid small' %>
			<div class="mentions"></div>
		<% end -%>

		<ul id="comments">
			<% @post.comments.recent.limit(10).all.each do |comment| %>
				<%= render 'partials/single_comment', locals: { comment: comment }  %>
			<% end %>
		</ul>
	</div>
</div>

<script>
	$('[data-post] [data-mentionable]').atwho({
		at: '@',
		data: '<%= mentionables_path %>',
		insertTpl: '@${username}',
		displayTpl: '<li data-id="${id}"><span>${username}</span></li>',
		callbacks: {
			beforeInsert: function(value, $li) {
				var user_id = $li.data('id');
				var mention = $('<input type="hidden" multiple="multiple" name="mentions[]" value="' + user_id + '"/>');
				$('form .mentions').append(mention);
				return value;
			}
		}
	});
</script>

app/views/post/visit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Blogular</title>
	<link rel="icon" type="image/png" href="<%= image_path 'favicon.png' %>" />
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body class="visit_frame">
	<header id="top" data-post-id="<%= @post.id %>">
		<div class="logo">
			<%= link_to root_path  do %>
				<%= image_tag 'logo.png' %>
			<% end -%>
		</div>

		<div class="tools actions">
			<%= link_to 'Comment', @post, class: 'btn' %>
			<%= link_to conditional_label(current_user.likes?(@post), 'Liked', 'Like'), like_post_path(@post), remote: true, class: "btn red like #{'liked' if current_user.likes?(@post)}", 'data-label-update': @post.id %>

			<% unless @post.blog.nil? %>
			<%= render 'partials/follow_button', locals: { subject: @post.blog } %>
			<% end -%>
		</div>
	</header>

  <%= @redirect %>

	<iframe src="<%= @post.url %>" frameborder="0" id="render"></iframe>

</body>
</html>