config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'blog/:id' => 'blog#show', as: :blog
  get 'blog/:id/comments' => 'blog#comments', as: :blog_comments
  post 'blog/:id/comments' => 'blog#comment', as: :blog_comment
  get 'blog/:id/follow' => 'blog#follow', as: :follow_blog
  get 'blog/:id/like' => 'blog#like', as: :like_blog
  get 'blog/:id/visit' => 'blog#visit', as: :visit_blog
  get 'blog/:id/has_new' => 'blog#has_new', as: :has_new

  get 'user/profile', as: :user_profile
  get 'user/profile/edit' => 'user#edit_profile', as: :edit_user_profile
  patch 'user/profile/edit' => 'user#patch_profile'
  get 'user/onboard' => 'user#onboard', as: :onboarding
  patch 'user/onboard' => 'user#patch_onboard'

  get 'user/:id/follow' => 'user#follow', as: :follow_user

  get 'user/likes'
  get 'user/:id/likes' => 'user#likes'

  get 'user/friends'
  get 'user/:id/friends' => 'user#friends'

  get 'user/blogs'
  get 'user/:id/blogs' => 'user#blogs'

  get 'user/:id' => 'user#profile', as: :user
  post 'user/notifications/read' => 'user#read_notifications', as: :read_notifications

  post 'post/:id/comment' => 'post#comment', as: :post_comment
  get 'post/:id' => 'post#show', as: :post
  get 'post/:id/like' => 'post#like', as: :like_post
  get 'post/:id/visit' => 'post#visit', as: :post_visit

  get 'share/scrape', as: :scrapper
  post 'share/share', as: :share
  get 'share/mentionables', as: :mentionables

  get 'feed/discover', as: :discover
  get 'feed/discover/posts' => 'feed#posts', as: :discover_posts
  get 'feed/discover/blogs' => 'feed#blogs', as: :discover_blogs
  get 'feed/discover/users' => 'feed#users', as: :discover_users
  get 'feed/discover/tags' => 'feed#tags', as: :discover_tags

  get 'search' => 'feed#search', as: :search

  root 'feed#home'
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  include PublicActivity::Common
  include PgSearch

  has_many :posts
  has_one :read_state, dependent: :delete

  acts_as_followable
  acts_as_likeable
  acts_as_commentable
  acts_as_taggable

  pg_search_scope :search,
                  against: [:title],
                  using: {
                    tsearch: { prefix: true },
                    trigram: {}
                  }


  def self.create_for_feed(data)
    if data[:feed].nil?
      return nil
    end

    blog = Blog.where(feed: data[:feed])

    if blog.length > 0
      return blog.first
    end

    site = Addressable::URI.parse(data[:url]).normalized_site.to_s

    begin
      feed = Feedjira::Feed.fetch_and_parse data[:feed]
    rescue
      begin
        feed = Feedjira::Feed.fetch_and_parse data[:url]
      rescue
        feed = false
      end
    end

    blog = Blog.new
    blog.feed = data[:feed]
    if feed
      blog.title = feed.title ? feed.title : data[:title]
    else
      blog.title = data[:title] ?  data[:title] : "[No Name]"
    end
    blog.url = site

    blog.save!

    return blog
  end

  def new_posts?(user)
    receipt = ReadState.where(blog: self, user: user)

    if receipt.count > 0
      time = receipt.first.last_read
    else
      return true
    end

    begin
      feed = Feedjira::Feed.fetch_and_parse(self.feed)
    rescue
      return false
    end

    latest = feed.entries.first

    if latest.nil?
      return false
    end

    return latest.published > time
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_filter :get_blog
  before_action :authenticate_user!

  def show
    @posts = @blog.posts.order(created_at: :desc)
                        .paginate(page: params[:page])
                        .per_page(6)
  end

  def comments
  end

  def comment
    comment = @blog.comments.create
    comment.comment = params[:comment]
    comment.user = current_user
    comment.save
    @comment = comment

    unless params[:mentions].nil?
      params[:mentions].each do |mention|
        user = User.find(mention)
        @comment.mention!(user)
        user.create_activity action: 'mention', recipient: @comment, owner: current_user
      end
    end
  end

  def follow
    @following = current_user.toggle_follow!(@blog)
  end

  def like
    @liked = current_user.toggle_like! @blog
  end

  def visit
    @blog = Blog.find(params[:id])
    frameoptions = HTTParty.get(@blog.url).headers['x-frame-options'];
    redirect = false

    unless frameoptions.nil?
       if frameoptions == 'SAMEORIGIN' or frameoptions == 'sameorigin'
          redirect = true
        end
    end

    unless @blog.nil?
      @receipt = ReadState.find_or_initialize_by(user_id: current_user.id, blog_id: @blog.id)
      @receipt.last_read = DateTime.now
      @receipt.save
    end

    unless redirect
      render 'blog/visit', layout: false
    else
      redirect_to @blog.url
    end
  end

  def has_new
    @blog = Blog.find(params[:id])
    render json: { has_new: @blog.new_posts?(current_user) }
  end

  private
  def get_blog
    @blog = Blog.find(params[:id])
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/_blog.html.erb
<div class="blog container">
	<div class="blog" data-blog="<%= @blog.id %>">
		<h1>
			<%= @blog.title %>
			<%= render 'partials/follow_button', locals: { subject: @blog } %>
		</h1>

		<p> <%= image_tag 'website.png' %><%= link_to @blog.url, visit_blog_path(@blog) %> </p>

		<%= yield %>

	</div>
</div>

app/views/blog/comment.js.erb
$('.comments ul').prepend($('<%= j render 'partials/single_comment', locals: { comment: @comment }  %>')).hide().fadeIn('slow');
$('.comments textarea').val('');
$('.expanded').removeClass('expanded');
$('.comments .mentions').empty();

app/views/blog/comments.html.erb
<%= render layout: 'blog' do %>
	<div class="comments">
		<header>
			<h2>Comments</h2>
		</header>

		<%= form_tag blog_comment_path(@blog), remote: true do %>
			<%= text_area_tag 'comment', nil, rows: 1, placeholder: 'Comment on this post', 'data-mentionable': 'true'  %>
			<%= submit_tag 'Post comment', class: 'btn solid small' %>
			<div class="mentions"></div>
		<% end -%>

		<ul id="comments">
			<% @blog.comments.recent.limit(10).all.each do |comment| %>
				<%= render 'partials/single_comment', locals: { comment: comment }  %>
			<% end %>
		</ul>
	</div>

	<script>
	$('[data-blog] [data-mentionable]').atwho({
		at: '@',
		data: '<%= mentionables_path %>',
		insertTpl: '@${username}',
		displayTpl: '<li data-id="${id}"><span>${username}</span></li>',
		callbacks: {
			beforeInsert: function(value, $li) {
				var user_id = $li.data('id');
				var mention = $('<input type="hidden" multiple="multiple" name="mentions[]" value="' + user_id + '"/>');
				$('form .mentions').append(mention);
				return value;
			}
		}
	});
	</script>
<% end -%>

app/views/blog/follow.js.erb
<% if @following %>
$('a[data-blog="<%= @blog.id %>"]').addClass('on').text('Following');
$('[data-blog-followers="<%= @blog.id %>"]').text('<%= @blog.followers_count + 1 %>');
<% else %>
$('a[data-blog="<%= @blog.id %>"]').removeClass('on').text('Follow');
$('[data-blog-followers="<%= @blog.id %>"]').text('<%= @blog.followers_count - 1 %>');
<% end  %>

app/views/blog/like.js.erb
<% if @liked %>
	$('[data-blog-id="<%= @blog.id %>"] .actions .like').addClass('liked').find('span').text('<%= @blog.likers_count + 1 %>');
<% else %>
	$('[data-blog-id="<%= @blog.id %>"] .actions .like').removeClass('liked').find('span').text('<%= @blog.likers_count - 1 %>');
<% end %>

$('[data-label-update="<%= @blog.id %>"]').text('<%= conditional_label(@liked, 'Liked', 'Like') %>');

app/views/blog/show.html.erb
<%= render layout: 'blog' do %>
	<h2>Posts shared by our users:</h2>

	<ul class="posts activity-feed grid" data-infinity="true">
		<%= render partial: 'partials/post', collection: @posts  %>
		<%= will_paginate @posts %>
	</ul>
<% end -%>

app/views/blog/visit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Blogular</title>
	<link rel="icon" type="image/png" href="<%= image_path 'favicon.png' %>" />
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body class="visit_frame">
	<header id="top" data-blog-id="<%= @blog.id %>">
		<div class="logo">
			<%= link_to root_path  do %>
				<%= image_tag 'logo.png' %>
			<% end -%>
		</div>

		<div class="tools actions">
			<%= link_to 'Comment', blog_comments_path(@blog), class: 'btn' %>
			<%= link_to conditional_label(current_user.likes?(@blog), 'Liked', 'Like'), like_blog_path(@blog), remote: true, class: "btn red like #{'liked' if current_user.likes?(@blog)}", 'data-label-update': @blog.id %>

			<% unless @blog.nil? %>
				<%= render 'partials/follow_button', locals: { subject: @blog } %>
			<% end -%>
		</div>
	</header>

	<%= @redirect %>
	<iframe src="<%= @blog.url %>" frameborder="0"  id="render"></iframe>


</body>
</html>